name: Publish to Thunderstore

on:
  workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # Need to fetch all for proper history
            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "9.0.x"
            -   name: Build and Create Thunderstore Package
                run: |
                    dotnet tool restore
                    dotnet cake
            -   name: Publish to Thunderstore
                run: |
                    ZIP_FILE=$(ls ./build/*.zip | head -1)
                    dotnet tcli publish --file "$ZIP_FILE"
                env:
                    TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}